### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by nay-n**
Translation improvements.

Not sure why there is a  "200$ USD" value hardcoded at line 465 in <string name="not_backed_up_detail"> .

### CODE REVIEW

**Comment by gichiba** [comment]
Huh that's an interesting observation... I wonder what that's about...

**Comment by gichiba** [comment]
From the discord: 
"It’s an arbitrary amount that we decided on in the earlier days, a threshold where we remind the users to backup (again)"

**Comment by gichiba** [comment]
Alright, if we find better translations along the way, we can open another PR -- I'm going to merge this so that we can move on and try to get it submitted to the upstream repo and into the next build of the alphawallet app

**Comment by nay-n** [comment]
I see. Makes sense now. Cheers..

**Pull request merged**
